-- seed.sql
-- Extended pre-loaded book catalog for the query engine.
-- Run this ONCE against a fresh database, then delete this file
-- (or stop referencing it in run_seed) to avoid duplicate inserts.

INSERT INTO books (title, genre, year, rating, author) VALUES
('Dom Casmurro', 'Fiction', 1899, 9.1, 'Machado de Assis'),
('1984', 'Dystopian', 1949, 9.3, 'George Orwell'),
('The Hobbit', 'Fantasy', 1937, 8.9, 'J.R.R. Tolkien'),
('The Lord of the Rings', 'Fantasy', 1954, 9.4, 'J.R.R. Tolkien'),
('Crime and Punishment', 'Fiction', 1866, 9.0, 'Fyodor Dostoevsky'),
('The Brothers Karamazov', 'Fiction', 1880, 9.2, 'Fyodor Dostoevsky'),
('Sapiens', 'Non-Fiction', 2011, 8.7, 'Yuval Noah Harari'),
('Homo Deus', 'Non-Fiction', 2015, 8.5, 'Yuval Noah Harari'),
('The Pragmatic Programmer', 'Technical', 1999, 9.2, 'Andrew Hunt'),
('Clean Code', 'Technical', 2008, 8.8, 'Robert C. Martin'),
('Clean Architecture', 'Technical', 2017, 8.7, 'Robert C. Martin'),
('Design Patterns', 'Technical', 1994, 8.9, 'Erich Gamma'),
('The Alchemist', 'Fiction', 1988, 8.4, 'Paulo Coelho'),
('Brave New World', 'Dystopian', 1932, 9.0, 'Aldous Huxley'),
('The Little Prince', 'Fiction', 1943, 9.1, 'Antoine de Saint-Exupery'),
('Meditations', 'Philosophy', 180, 8.9, 'Marcus Aurelius'),
('The Republic', 'Philosophy', -380, 8.8, 'Plato'),
('Thus Spoke Zarathustra', 'Philosophy', 1883, 8.6, 'Friedrich Nietzsche'),
('The Selfish Gene', 'Science', 1976, 8.6, 'Richard Dawkins'),
('A Brief History of Time', 'Science', 1988, 8.9, 'Stephen Hawking'),
('Cosmos', 'Science', 1980, 8.8, 'Carl Sagan'),
('Neuromancer', 'Sci-Fi', 1984, 8.5, 'William Gibson'),
('Dune', 'Sci-Fi', 1965, 9.3, 'Frank Herbert'),
('Foundation', 'Sci-Fi', 1951, 9.0, 'Isaac Asimov'),
('Fahrenheit 451', 'Dystopian', 1953, 8.8, 'Ray Bradbury'),
('The Art of War', 'Philosophy', -500, 8.3, 'Sun Tzu'),
('Meditations on First Philosophy', 'Philosophy', 1641, 8.1, 'Rene Descartes'),
('Atomic Habits', 'Non-Fiction', 2018, 8.9, 'James Clear'),
('The Power of Habit', 'Non-Fiction', 2012, 8.4, 'Charles Duhigg'),
('Thinking, Fast and Slow', 'Non-Fiction', 2011, 8.7, 'Daniel Kahneman'),
('Man''s Search for Meaning', 'Non-Fiction', 1946, 9.0, 'Viktor Frankl'),
('One Hundred Years of Solitude', 'Fiction', 1967, 9.1, 'Gabriel Garcia Marquez'),
('Love in the Time of Cholera', 'Fiction', 1985, 8.7, 'Gabriel Garcia Marquez'),
('The Great Gatsby', 'Fiction', 1925, 8.8, 'F. Scott Fitzgerald'),
('To Kill a Mockingbird', 'Fiction', 1960, 9.0, 'Harper Lee'),
('Moby Dick', 'Fiction', 1851, 8.5, 'Herman Melville'),
('War and Peace', 'Fiction', 1869, 9.0, 'Leo Tolstoy'),
('Anna Karenina', 'Fiction', 1877, 8.9, 'Leo Tolstoy'),
('The Odyssey', 'Fiction', -800, 8.7, 'Homer'),
('The Iliad', 'Fiction', -750, 8.6, 'Homer'),
('Pride and Prejudice', 'Fiction', 1813, 8.8, 'Jane Austen'),
('Frankenstein', 'Sci-Fi', 1818, 8.4, 'Mary Shelley'),
('Do Androids Dream of Electric Sheep?', 'Sci-Fi', 1968, 8.3, 'Philip K. Dick'),
('The Handmaid''s Tale', 'Dystopian', 1985, 8.9, 'Margaret Atwood'),
('Slaughterhouse-Five', 'Fiction', 1969, 8.6, 'Kurt Vonnegut'),
('Catch-22', 'Fiction', 1961, 8.7, 'Joseph Heller'),
('The Catcher in the Rye', 'Fiction', 1951, 8.2, 'J.D. Salinger'),
('Notes from Underground', 'Fiction', 1864, 8.3, 'Fyodor Dostoevsky'),
('The Stranger', 'Fiction', 1942, 8.5, 'Albert Camus'),
('The Myth of Sisyphus', 'Philosophy', 1942, 8.4, 'Albert Camus'),
('Sapiens: A Graphic History', 'Non-Fiction', 2020, 8.2, 'Yuval Noah Harari'),
('Zero to One', 'Non-Fiction', 2014, 8.3, 'Peter Thiel'),
('The Lean Startup', 'Non-Fiction', 2011, 8.1, 'Eric Ries'),
('Deep Work', 'Non-Fiction', 2016, 8.5, 'Cal Newport'),
('The Innovators Dilemma', 'Non-Fiction', 1997, 8.2, 'Clayton Christensen'),
('Introduction to Algorithms', 'Technical', 1990, 9.0, 'Thomas Cormen'),
('Structure and Interpretation of Computer Programs', 'Technical', 1985, 8.9, 'Harold Abelson'),
('The Mythical Man-Month', 'Technical', 1975, 8.6, 'Frederick Brooks'),
('Refactoring', 'Technical', 1999, 8.5, 'Martin Fowler'),
('You Don''t Know JS', 'Technical', 2014, 8.4, 'Kyle Simpson'),
('Eloquent JavaScript', 'Technical', 2011, 8.3, 'Marijn Haverbeke');
